automated upload processing
File processing triggered on upload and different stages can be
triggered in sequence via configuration.

commit 93b7f6f412dc8b970195883180db5c8e3f76a99c
Author: Marco La Rosa <m@lr.id.au>
Date:   Fri Nov 19 12:07:06 2021 +1100

    fix transcription file names

commit 2f8c0b67ed5ae2eb73d4850fd06814c66d55440e
Author: Marco La Rosa <m@lr.id.au>
Date:   Fri Nov 19 12:01:04 2021 +1100

    fix ref to thumbnail image

commit d9c27015a46bb1970ccc3dab8a9c63d62b5eeb80
Author: Marco La Rosa <m@lr.id.au>
Date:   Fri Nov 19 11:30:01 2021 +1100

    update example configuration

commit 46e10d5e419d4a1d4e6cd0fe0edc1fae02e2df5c
Author: Marco La Rosa <m@lr.id.au>
Date:   Fri Nov 19 11:28:46 2021 +1100

    revise to match updated config

commit eb23bf8ded19d8062d342d528e897284d3cc5946
Author: Marco La Rosa <m@lr.id.au>
Date:   Fri Nov 19 11:27:58 2021 +1100

    refactor

    * move processing code to lib
    * wire up routes to match tus stage hooks

commit 80e3372e942f985de9c89030389032d0f84ab38f
Author: Marco La Rosa <m@lr.id.au>
Date:   Fri Nov 19 11:27:34 2021 +1100

    catch auth errors

commit a8dc29a058c516b94c8d29a354a83fb07019d502
Author: Marco La Rosa <m@lr.id.au>
Date:   Fri Nov 19 11:27:01 2021 +1100

    refactor layout; trigger next processing stage if defined

commit dd0035d69ac8cb6925470b953ab98238f4a96e10
Author: Marco La Rosa <m@lr.id.au>
Date:   Fri Nov 19 11:22:34 2021 +1100

    add POST_FINISH variable to rabbit worker

commit cda065f51633fdc3fdabe2b0b3fdd94386a368d6
Author: Marco La Rosa <m@lr.id.au>
Date:   Thu Nov 18 13:09:29 2021 +1100

    check task id is set on the body

commit 9fd9b34c386f4c3bd418940341a5755842f38259
Author: Marco La Rosa <m@lr.id.au>
Date:   Thu Nov 18 12:56:40 2021 +1100

    refactor upload and data processing routes

commit 54088592b39dc534fce2a960aa1deb53a9593927
Author: Marco La Rosa <m@lr.id.au>
Date:   Thu Nov 18 12:56:19 2021 +1100

    refactor tus env configuration

commit 155ee284d14e79a91ae66e309b3f213efd9867e7
Author: Marco La Rosa <m@lr.id.au>
Date:   Thu Nov 18 12:55:32 2021 +1100

    revise tus hook scripts

    * better checking
    * refactor hook notifications back to api

diff --git a/tus/post-finish b/tus/post-finish
--- a/tus/post-finish
+++ b/tus/post-finish
@@ -1,24 +1,50 @@
 #!/bin/bash
-for file in $(ls /data/${TUS_ID}*) ; do
-    # skip .info files
-    [[ "${file}" == "/data/${TUS_ID}.info" ]] && continue
 
-    # if data file extract filename and item id from .info
-    if [ "${file}" == "/data/${TUS_ID}" ] ; then
-        itemId=$(cat "/data/${TUS_ID}.info" | jq .MetaData.itemId | sed -e 's/"//g')
-        filename=$(cat "/data/${TUS_ID}.info" | jq .MetaData.filename | sed -e 's/"//g')
-
-        # copy to s3
-        if [ ! -z ${S3_ENDPOINT_URL} ] ; then
-            aws --endpoint-url "${S3_ENDPOINT_URL}" s3 cp "${file}" "s3://${S3_BUCKET}/${itemId}/${filename}"
-        else
-            aws s3 cp "${file}" "s3://${S3_BUCKET}/${itemId}/${filename}"
-        fi
-
-        # cleanup - remove data file and .info
-        if [ $? == 0 ] ; then
-            rm -f "${file}"
-            rm -f "${file}.info"
-        fi
+check() {
+    variable=$1
+    if [ -z ${variable} ] ; then
+        echo "'\${variable} is unset. Exiting"
+        exit -1
     fi
-done
+}
+
+cleanup() {
+  file=${1}
+
+  # cleanup - remove data file and .info
+  rm -f "${file}"
+  rm -f "${file}.info"
+}
+
+check AWS_ACCESS_KEY_ID
+check AWS_SECRET_ACCESS_KEY
+check AWS_DEFAULT_REGION
+check S3_BUCKET
+
+file="/data/${TUS_ID}"
+
+if [ -f "${file}" ] ; then
+    itemId=$(cat "${file}.info" | jq .MetaData.itemId | sed -e 's/"//g')
+    filename=$(cat "${file}.info" | jq .MetaData.filename | sed -e 's/"//g')
+    token=$(cat "${file}.info" | jq .MetaData.token | sed 's/"//g')
+
+    if [ -z ${token} ] ; then
+        echo "Can't get user token from metadata. Access denied by default."
+        exit -1
+    fi
+
+    # copy to s3
+    if [ ! -z ${S3_ENDPOINT_URL} ] ; then
+        aws --endpoint-url "${S3_ENDPOINT_URL}" s3 cp "${file}" "s3://${S3_BUCKET}/${itemId}/${filename}"
+        [[ $? != 0 ]] && cleanup ${file} && exit -1
+    else
+        aws s3 cp "${file}" "s3://${S3_BUCKET}/${itemId}/${filename}"
+        [[ $? != 0 ]] && cleanup ${file} && exit -1
+    fi
+
+    if [ ! -z "${POST_FINISH}" ] ; then
+        curl --silent --header "authorization: Bearer ${token}" "${POST_FINISH}/${itemId}"
+    fi
+    cleanup ${file}
+
+fi
