implement item resource list component
commit 1808fa5180eae1b70f544e361ce22f68b630fbee
Author: Marco La Rosa <m@lr.id.au>
Date:   Mon Aug 30 10:27:15 2021 +1000

    implement item resource list component

commit 1b0266c11fd2967c70ed300dda3ae4692c9001e2
Author: Marco La Rosa <m@lr.id.au>
Date:   Mon Aug 30 10:27:08 2021 +1000

    bugfix

commit 59029eb9d6ce59e44b7f586ca819afa8cb591d31
Author: Marco La Rosa <m@lr.id.au>
Date:   Mon Aug 30 10:26:38 2021 +1000

    rework as tabs

commit 7e2ccdb2b7f480c71b24b467cc0a1b189b76aa5b
Author: Marco La Rosa <m@lr.id.au>
Date:   Mon Aug 30 10:26:10 2021 +1000

    disable debug mode

commit 0fb95f0df3dfd6967e2ee739318013c938ce19a5
Author: Marco La Rosa <m@lr.id.au>
Date:   Mon Aug 30 10:20:52 2021 +1000

    revise config for updated dev server package

commit f289515d300f12f6255db5be02c62340095f0d3e
Author: Marco La Rosa <m@lr.id.au>
Date:   Mon Aug 30 10:20:36 2021 +1000

    encore route uri and add debug statement

commit 824afd1dbc3c4a4df65c89d7cac1a0010b5a1eae
Author: Marco La Rosa <m@lr.id.au>
Date:   Mon Aug 30 10:20:12 2021 +1000

    update path to theme css

commit b07e6b15a93773c4a8a2d79e280f363e6f601208
Author: Marco La Rosa <m@lr.id.au>
Date:   Mon Aug 30 10:19:52 2021 +1000

    strip path from item resources

commit 2201507ee1d4bb4b2335f89534fbe1d2815abf46
Author: Marco La Rosa <m@lr.id.au>
Date:   Mon Aug 30 10:19:34 2021 +1000

    update dependencies

commit d02af20575e07ee52f756c8e1588743373f3f110
Author: Marco La Rosa <m@lr.id.au>
Date:   Fri Aug 27 07:46:20 2021 +1000

    revise s3 upload to name files as per their actual name

commit c3d20335d13d0f07abf8d6889a95cd627265e7fb
Author: Marco La Rosa <m@lr.id.au>
Date:   Thu Aug 26 16:10:05 2021 +1000

    implement methods to get resource list for given item

commit 96ed00e2c8f665f19c49f725399db8f61676ba7f
Author: Marco La Rosa <m@lr.id.au>
Date:   Thu Aug 26 16:09:54 2021 +1000

    implement s3 lib

commit 5986fe3d4bacb5f0773d0e161fbbd4afc944112c
Author: Marco La Rosa <m@lr.id.au>
Date:   Thu Aug 26 16:09:27 2021 +1000

    implement method to get s3 handle

diff --git a/tus/post-finish b/tus/post-finish
--- a/tus/post-finish
+++ b/tus/post-finish
@@ -1,12 +1,24 @@
-#!/bin/ash
-for file in $(ls /data/$TUS_ID*) ; do
-    itemId=$(cat /data/${TUS_ID}.info | jq .MetaData.itemId | sed -e 's/"//g')
-    if [ ! -z ${S3_ENDPOINT_URL} ] ; then
-        aws --endpoint-url ${S3_ENDPOINT_URL} s3 cp $file s3://uploads/${itemId}/
-    else 
-        aws s3 cp $file s3://uploads/${itemId}/
-    fi
-    if [ $? == 0 ] ; then
-        rm -f $file
+#!/bin/bash
+for file in $(ls /data/${TUS_ID}*) ; do
+    # skip .info files
+    [[ "${file}" == "/data/${TUS_ID}.info" ]] && continue
+
+    # if data file extract filename and item id from .info
+    if [ "${file}" == "/data/${TUS_ID}" ] ; then
+        itemId=$(cat "/data/${TUS_ID}.info" | jq .MetaData.itemId | sed -e 's/"//g')
+        filename=$(cat "/data/${TUS_ID}.info" | jq .MetaData.filename | sed -e 's/"//g')
+
+        # copy to s3
+        if [ ! -z ${S3_ENDPOINT_URL} ] ; then
+            aws --endpoint-url "${S3_ENDPOINT_URL}" s3 cp "${file}" "s3://uploads/${itemId}/${filename}"
+        else
+            aws s3 cp "${file}" "s3://uploads/${itemId}/${filename}"
+        fi
+
+        # cleanup - remove data file and .info
+        if [ $? == 0 ] ; then
+            rm -f "${file}"
+            rm -f "${file}.info"
+        fi
     fi
 done
